image: node:23-alpine

# Define stages
stages:
  - setup
  - test
  - build
  - deploy

# Cache configuration
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - app/node_modules/

# Setup stage
setup:
  stage: setup
  before_script:
    - apk add --no-cache python3 make g++
  script:
    - cd app
    - npm ci
  artifacts:
    expire_in: 1 week

# Lint and type checking
lint:
  stage: test
  script:
    - cd app
    - npm run lint
    - npm run type-check
  dependencies:
    - setup

# Unit tests
test:
  stage: test
  script:
    - cd app
    - npm test -- --ci
  dependencies:
    - setup

# Web build
web_build:
  stage: build
  script:
    - cd app
    - npm run build
    - if [ ! -d "dist" ]; then echo "Web build failed"; exit 1; fi
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  dependencies:
    - setup

# Rules for when to run pipelines
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH =~ /^feature\/.*$/
    - if: $CI_COMMIT_BRANCH =~ /^bugfix\/.*$/
    - if: $CI_COMMIT_TAG 