stages:
  - test

test:
  stage: test
  image: python:3.13-slim
  before_script:
    - pip install uv
    - cd /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/back
    - uv sync
  script:
    - uv run pytest
