[project]
name = "back"
version = "0.1.0"
description = "FastAPI backend for the SNCF Incident Reporting App"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "pydantic>=2.11.4",
    "pytest>=8.3.5",
    "requests>=2.32.3",
]
